=== bertjwregeer/guides/guide-01.dtd
<?xml encoding="UTF-8" ?>
<!--
 Guide
 
 @author X-Istence <xistence@0x58.com>
 @url http://0x58.com/
 @copyright 2005
 @license http://license.0x58.com/public/
 
 Public Identifier "-//0x58//DTD guide//EN"
 Link Path "http://dtd.0x58.com/guide-01.dtd"
 Declaration:
     <!DOCTYPE guide PUBLIC "-//0x58//DTD guide//EN" "http://dtd.0x58.com/guide-01.dtd">
 
 Version History:
 1.1 - Added license. That way authors can let people know what license it is under. No name change, i am only one using it still.
 1.0 - Initial Creation
     Some basics for any type of guide. Was originally coined for use by http://bsdguides.org/
 -->


<!-- Starting tag. Do note we can have multiple authors! -->
<!ELEMENT guide (title, author+, date, revisions?, body)>
<!ATTLIST guide
				xmlns:xlink	CDATA	#FIXED	"http://www.w3.org/1999/xlink">

<!-- Title for the guide/section of the guide -->
<!ELEMENT title (#PCDATA)>
<!-- Author's name -->
<!ELEMENT author (name+, email?, license?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ATTLIST email
					user	CDATA	#REQUIRED
					domain	CDATA	#REQUIRED>
        <!ELEMENT license (#PCDATA)>
        <!ATTLIST license
					url     CDATA   #REQUIRED>

<!-- Date the guide was created on, should we include a last modified? Or can we just update this field? -->
<!ELEMENT date (#PCDATA)>

<!ELEMENT revisions (revitem+)>
<!ELEMENT revitem (#PCDATA)>
<!ATTLIST revitem
				importance    CDATA   #REQUIRED>

<!-- Main body where everything happens, it requires at least one section! -->
<!ELEMENT body (section+)>

<!-- Section requires a title, and a paragraph tag. -->
<!ELEMENT section (title, paragraph)>

<!-- Paragraph can contain as many of the elements text, exec, config, and or tip as one wants -->
<!ELEMENT paragraph (text | exec | config | tip)+>
<!ELEMENT text (#PCDATA|list|link)*>
<!ELEMENT exec (#PCDATA)>
<!ELEMENT config (#PCDATA)>
<!ATTLIST config
				location	CDATA	#REQUIRED>
				
<!ELEMENT tip (#PCDATA|list|link)*>

<!ELEMENT list (item+)>
<!ATTLIST list
               type	CDATA	#REQUIRED>
               
<!ELEMENT item (#PCDATA|link)*>

<!ELEMENT link (#PCDATA)>
<!ATTLIST link
               xlink:type	CDATA	#FIXED        "simple"
               xlink:href	CDATA	#REQUIRED
               xlink:show	CDATA	#REQUIRED>

<!ENTITY spc4 "&#x20;&#x20;&#x20;&#x20;">
<!ENTITY spc8 "&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;">

=== bertjwregeer/guides/daemontools.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE guide PUBLIC "-//0x58//DTD guide//EN" "http://dtd.0x58.com/guide-01.dtd">
<?xml-stylesheet href="./.guides.xsl" type="text/xsl" ?>

<guide xmlns:xlink="http://www.w3.org/1999/xlink">
	<title>daemontools</title>
	<author>
		<name>Jan-Willem Regeer</name>
		<email user="xistence" domain="x-istence.com" />
		<license url="http://creativecommons.org/licenses/by-nc-sa/2.5/" year="2005">Creative Commons Attribution-NonCommercial-ShareAlike 2.5 </license>
	</author>
	<date>2005-08-31, 11:58</date>        
	
	<body>
		<section>
			<title>General Information</title>
			<paragraph>
			<text>This guide will help you set up <link xlink:type="simple" xlink:href="http://cr.yp.to/" xlink:show="replace">Dan Bernstein's</link> daemontools. Which is a program that supervises another daemon so that when it does fail, it will automatically be restarted.</text>
			</paragraph>
		</section>
		<section>
			<title>Requirements</title>
			<paragraph>
				<text>You will need the following items to be able to complete this guide:
					<list type="ordered">
						<item>Root access to a FreeBSD machine</item>
						<item>FreeBSD install with <link xlink:type="simple" xlink:href="./updatingports" xlink:show="replace">ports up-to-date</link> </item>
					</list>
				</text>
			</paragraph>
		</section>
		<section>
			<title>Compiling</title>
			<paragraph>
				<text>This is where your up-to-date ports come in handy.</text>
				<exec>cd /usr/ports/sysutils/daemontools
make install</exec>
			</paragraph>
		</section>
		<section>
			<title>Setting up daemontools</title>
			<paragraph>
				<text>There is not much to do. Create a directory, and then we also need to add an entry to /etc/rc.conf to tell it that we want to start svscan, as the master process is called, upon booting.</text>
				<exec>mkdir /var/services</exec>
				<config location="/etc/rc.conf">svscan_enable="YES"</config>
			</paragraph>
		</section>
		<section>
			<title>Starting svscan</title>
			<paragraph>
				<text>There are two ways that you can start svnscan. Reboot your system, or execute it's rc file.</text>
				<exec>/usr/local/etc/rc.d/svscan.sh start</exec>
				<text>It should now be running, to see if it really is running, check with ps.</text>
				<exec>ps auxwwww | grep svscan</exec>
				<text>You should see /usr/local/bin/svscan running. Congratulations, you successfully got daemontools running.</text>
			</paragraph>
		</section>
	</body>
</guide>

=== bertjwregeer/guides/folding@home.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE guide PUBLIC "-//0x58//DTD guide//EN" "http://dtd.0x58.com/guide-01.dtd">
<?xml-stylesheet href="./.guides.xsl" type="text/xsl" ?>

<guide xmlns:xlink="http://www.w3.org/1999/xlink">
	<title>Folding@Home using daemontools</title>
	<author>
		<name>Jan-Willem Regeer</name>
		<email user="xistence" domain="x-istence.com" />
		<license url="http://creativecommons.org/licenses/by-nc-sa/2.5/" year="2005">Creative Commons Attribution-NonCommercial-ShareAlike 2.5 </license>
	</author>
	<date>2005-10-20, 20:56</date>        
	
	<body>
		<section>
			<title>General Information</title>
			<paragraph>
			<text>This guide will help you set up <link xlink:type="simple" xlink:href="http://folding.stanford.edu/" xlink:show="replace">Folding@Home</link> using <link xlink:type="simple" xlink:href="http://cr.yp.to/daemontools.html" xlink:show="replace">Dan Bernstein's daemontools</link>, for easy maintenance and also so that on a server reboot folding@home automatically comes back up.</text>
			</paragraph>
		</section>
		<section>
			<title>Requirements</title>
			<paragraph>
				<text>You will need the following items to be able to complete this guide:
					<list type="ordered">
						<item>Root access to a FreeBSD machine</item>
						<item><link xlink:type="simple" xlink:href="./daemontools" xlink:show="replace">Daemontools running</link></item>
						<item>Linux compatibility installed</item>
					</list>
				</text>
			</paragraph>
		</section>
		<section>
			<title>Installing Linux Compat</title>
			<paragraph>
				<text>Folding@home only makes Linux binaries, if you do not have the Linux emulation mode enabled, then run the following command:</text>
				<exec>pkg_add -r linux_base-8
echo 'linux_enable="YES"' >> /etc/rc.conf</exec>
				<tip>If you wish, you can compile from source, using the /usr/ports/emulators/linux_base-8/</tip>
				<text>At this point you need to restart, for the new linux emulation mode to become enabled.</text>
				<exec>shutdown -r now</exec>
			</paragraph>
		</section>
		<section>
			<title>Setting up Folding@home</title>
			<paragraph>
				<text>Here one creates the service directory and also a directory where the Folding@home client is run.</text>
				<exec>mkdir /usr/local/folding@home/
mkdir /usr/local/folding@home/root</exec>
				<text>Next we need to get the binary. Yes this is the Linux binary eventhough it contains an .exe extension.</text>
				<exec>cd /usr/local/folding@home/root/
fetch http://www.stanford.edu/group/pandegroup/release/FAH502-Linux.exe
chmod +x FAH502-Linux.exe
brandelf -t Linux FAH502-Linux.exe</exec>
				<tip>You can always get the latest version of the client at <link xlink:type="simple" xlink:href="http://folding.stanford.edu/download.html" xlink:show="replace">http://folding.stanford.edu/download.html</link></tip>
				<exec>mkdir /usr/local/folding@home/log
mkdir /usr/local/folding@home/env
mkdir /usr/local/folding@home/log/main</exec>
				<text>We create the directory structure needed for folding@home to be run under Dan Bernstein's daemontools. We also need to chown/chmod them to the right permissions:</text>
				<exec>cd /usr/local/folding@home
chown -R nobody:nobody root env log/main
chmod 2755 root log log/main</exec>
				<text>Now before doing anything else, we need to get the client set up. You need to give it a username to be able to say that you contributed, or you can stay anonymous.</text>
			<exec>cd root
setuidgid nobody ./FAH502-Linux.exe -configonly
cd ..</exec>
			<text>Next set up the run file, this is the most important file, as it runs your Folding@home client using daemontools' supervise, which will make sure it is always up.</text>
			<exec>cat &lt;&lt; EOF &gt; run
#!/bin/sh
exec 2&gt;&amp;1
exec envdir ./env sh -c '
  cd /usr/local/folding@home/root/
  exec setuidgid nobody /usr/bin/nice -n 20 /usr/local/folding@home/root/FAH502-Linux.exe -freeBSD
'
EOF
chmod 700 run</exec>
			<text>Logging is important. Off course we want to know how far along we are.</text>
			<exec>cat &lt;&lt; EOF &gt; log/run
#!/bin/sh
exec setuidgid nobody multilog t ./main
EOF
chmod 700 log/run</exec>
			</paragraph>
		</section>
		<section>
			<title>Starting Folding@home</title>
			<paragraph>
				<text>Now, to get Folding@Home started using svscan and have it running under supervise, we have to let svscan know about our service.</text>
				<exec>cd /var/service
ln -s /usr/local/folding@home</exec>
				<text>It should now be running, to see if it really is running, check with ps.</text>
				<exec>ps auxwwww | grep -i fah</exec>
				<text>You should see several different processes named FAH*-Core.exe, this means you are good to go. To check how long it has been running use svstat like follows:</text>
			<exec>svstat /var/service/folding@home/</exec>
			</paragraph>
		</section>
	</body>
</guide>

=== bertjwregeer/guides/postgresql.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE guide PUBLIC "-//0x58//DTD guide//EN" "http://dtd.0x58.com/guide-01.dtd">
<?xml-stylesheet href="./.guides.xsl" type="text/xsl" ?>

<guide xmlns:xlink="http://www.w3.org/1999/xlink">
	<title>PostgreSQL 8.0</title>
	<author>
		<name>Jan-Willem Regeer</name>
		<email user="xistence" domain="x-istence.com" />
		<license url="http://creativecommons.org/licenses/by-nc-sa/2.5/" year="2005">Creative Commons Attribution-NonCommercial-ShareAlike 2.5 </license>
	</author>
	<date>2005-09-21, 15:26</date>        
	
	<body>
		<section>
			<title>General Information</title>
			<paragraph>
			<text>This guide will help you set up, and start running <link xlink:type="simple" xlink:href="http://postgresql.org/" xlink:show="replace">PostgreSQL</link> using the ports tree.</text>
			<tip>For information of how to use PostgreSQL try google. This guide will not help you with PostgreSQL past installing it</tip>
			</paragraph>
		</section>
		<section>
			<title>Requirements</title>
			<paragraph>
				<text>You will need the following items to be able to complete this guide:
					<list type="ordered">
						<item>Root access to a FreeBSD machine</item>
						<item>FreeBSD install with <link xlink:type="simple" xlink:href="./updatingports" xlink:show="replace">ports up-to-date</link></item>
					</list>
				</text>
			</paragraph>
		</section>
		<section>
			<title>Compiling</title>
			<paragraph>
				<text>This is where your up-to-date ports come in handy.</text>
				<exec>cd /usr/ports/databases/postgresql80-server/
make install</exec>
			</paragraph>
		</section>
		<section>
			<title>Setting up PostgreSQL</title>
			<paragraph>
				<text>There is little to do for the PostrgreSQL set up, but these steps are required. You could go with the defaults in the rc script, but that leaves you open for attack from local untrusted users.</text>
				<exec>mkdir /usr/local/pgsql/data
chown pgsql:pgsql /usr/local/pgsql/data
su -l pgsql -c "initdb -D /usr/local/pgsql/data -W -A md5"
echo 'postgresql_enable="YES"' >> /etc/rc.conf</exec>
				<text>This initializes the database, and lets you set the "super user" password, as well as telling PostgreSQL to only allow authentication if the client sends a md5 encrypted password. This is for security if you are going to be accessing it over the network.</text>
			</paragraph>
		</section>
		<section>
			<title>Starting PostgreSQL</title>
			<paragraph>
				<text>There are two ways that you can start PostgreSQL. Reboot your system, or execute it's rc file.</text>
				<exec>/usr/local/etc/rc.d/010.postgresql.sh start</exec>
				<text>It should now be running, to see if it really is running, check with ps.</text>
				<exec>ps auxwwww | grep postmaster</exec>
				<text>You should see a postmaster process running. That is what the postgresql people called their server, don't ask why!</text>
			</paragraph>
		</section>
		<section>
			<title>Using PostgreSQL</title>
			<paragraph>
				<text>Using PostgreSQL can be done one of two ways. One way is to install phpPgAdmin, which allows you to use a web interface to add users, add databases, and other such neat features, or one can make use of the psql tool that is available</text>
				<exec>psql &lt;dbname&gt; &lt;username&gt;</exec>
				<text>I will not walk you through adding users to psql, or even executing queries, there are excellent sources out there on the web just for that, one of them is the <link xlink:type="simple" xlink:href="http://postgresql.org/" xlink:show="replace">PostgreSQL documentation</link>.</text>
			</paragraph>
		</section>
	</body>
</guide>

=== bertjwregeer/guides/dnscache.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE guide PUBLIC "-//0x58//DTD guide//EN" "http://dtd.0x58.com/guide-01.dtd">
<?xml-stylesheet href="./.guides.xsl" type="text/xsl" ?>

<guide xmlns:xlink="http://www.w3.org/1999/xlink">
	<title>djbdns dnscache</title>
	<author>
		<name>Bert JW Regeer</name>
		<email user="xistence" domain="gmail.com" />
		<license url="http://creativecommons.org/licenses/by-nc-sa/2.5/" year="2005">Creative Commons Attribution-NonCommercial-ShareAlike 2.5</license>
	</author>
	<date>2005-08-29, 20:29</date>        
	
	<body>
		<section>
			<title>General Information</title>
			<paragraph>
			<text>This guide will walk you through setting up a DJB dnscache resolver.</text>
			</paragraph>
		</section>
		<section>
			<title>Requirements</title>
			<paragraph>
				<text>You will need the following items to be able to complete this guide:
					<list type="ordered">
						<item>Root access to a FreeBSD machine</item>
						<item>FreeBSD install with <link xlink:type="simple" xlink:href="./updatingports" xlink:show="replace">ports up-to-date</link> </item>
						<item>Installed and running <link xlink:type="simple" xlink:href="./daemontools" xlink:show="replace">daemontools (svscan)</link> </item>
					</list>
				</text>
			</paragraph>
		</section>
		<section>
			<title>Compiling</title>
			<paragraph>
				<text>Here is where your up to date port tree comes in handy, this we are just going to compile the djbdns package. From the options that show up, pick those that you wish to apply, the standards should suffice, unless you wish to host ipv6 IP addresses using tinydns, in which case you might want to select that.</text>
				<exec>cd /usr/ports/dns/djbdns
make install</exec>
				<tip>If you want to change what you compiled djbdns with next time, but it says that you have a saved config. Type "make rmconfig" to remove the saved options, and the next time you compile again, you will once again be asked for the options</tip>
			</paragraph>
		</section>
		<section>
			<title>Adding required users/groups</title>
			<paragraph>
				<text>We are adding the following groups/users to be used when configuring dnscache. If you do not add these users, you can't use dnscache!</text>
				<exec>pw groupadd nofiles -g 800
pw useradd dnslog -u 810 -g 800 -c "Logging for dns" -d /usr/local/djbdns/ -s /sbin/nologin
pw useradd dnscache -u 811 -g 800 -c "dnscache" -d /usr/local/djbdns/ -s /sbin/nologin</exec>
				<tip>Look at "pw userdel help" for info on removing these users if you decide to undo this entire install.</tip>
			</paragraph>
		</section>
		<section>
			<title>Setting up dnscache</title>
			<paragraph>
				<text>You can install dnscache anywhere. My personal place to put all of my tinydns/dnscache instances is in /usr/local/djbdns, so if you want yours elsewhere, please modify the following commands</text>
				<exec>mkdir /usr/local/djbdns
dnscache-conf dnscache dnslog /usr/local/djbdns/dnscache 127.0.0.1</exec>
				<text>This tells dnscache it should create the directory with everything in it at /usr/local/djbdns/dnscache, using dnscache as the user to run under when started with svnscan, and to use dnslog as the user to write the log files to the HD with. The ip address on the end is the IP it has to bind to when it starts up. If you want to let other clients connect to your dnscache server to resolve their stuff, then you need to bind it to an outward facing IP.</text>
			</paragraph>
		</section>
		<section>
			<title>Starting dnscache</title>
			<paragraph>
				<text>Tell svnscan about dnscache. Then wait 5 seconds, and dnscache should be running.</text>
				<exec>ln -s /usr/local/djbdns/dnscache /var/service</exec>
				<text>Well, since it is now hopefully running, we should test if it works.</text>
				<exec>dig @127.0.0.1 0x58.com</exec>
				<text>If you get an answer, pat yourself on the back, as dnscache is properly running, unless off course BIND answered that, but unless you enabled BIND, it should not be running. To set your dnscache as your nameserver for the entire OS, add an entry to /etc/resolv.conf</text>
				<config location="/etc/resolv.conf">nameserver 127.0.0.1</config>
				<text>Now do the test with dig again, this time leave out the @ symbol, and look for ;; SERVER: 127.0.0.1#53(127.0.0.1)</text>
				<exec>dig 0x58.com</exec>
				<text>That's it!</text>
			</paragraph>
		</section>
	</body>
</guide>

=== bertjwregeer/guides/openvpn.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE guide PUBLIC "-//0x58//DTD guide//EN" "http://dtd.0x58.com/guide-01.dtd">
<?xml-stylesheet href="./.guides.xsl" type="text/xsl" ?>

<guide xmlns:xlink="http://www.w3.org/1999/xlink">
	<title>OpenVPN 2</title>
	<author>
		<name>Bert JW Regeer</name>
		<email user="xistence" domain="x-istence.com" />
		<license url="http://creativecommons.org/licenses/by-nc-sa/2.5/" year="2007">Creative Commons Attribution-NonCommercial-ShareAlike 2.5 </license>
	</author>
	<date>2007-12-19, 03:02</date>        
	
	<body>
		<section>
			<title>General Information</title>
			<paragraph>
			<text>This guide will help you set up <link xlink:type="simple" xlink:href="http://openvpn.net/" xlink:show="replace">OpenVPN</link> to allow remote users to securely connect to the internal lan or use the VPN tunnel as an endpoint when on insecure wireless access points, allowing safe transmission of data without worries of being sniffed or intercepted.</text>
			</paragraph>
		</section>
		<section>
			<title>Requirements</title>
			<paragraph>
				<text>You will need the following items to be able to complete this guide:
					<list type="ordered">
						<item>Root access to a FreeBSD machine</item>
						<item>FreeBSD install with <link xlink:type="simple" xlink:href="./updatingports" xlink:show="replace">ports up-to-date</link></item>
						<item>Bash installed</item>
					</list>
				</text>
			</paragraph>
		</section>
		<section>
			<title>Compiling</title>
			<paragraph>
				<text>We only have one thing to compile.</text>
				<exec>cd /usr/ports/security/openvpn
make install clean</exec>
			</paragraph>
		</section>
		<section>
			<title>Server Configuration</title>
			<paragraph>
				<text>First things first, we need a directory to store the configuration files and keys, so lets create that directory structure</text>
				<exec>cd /usr/local/etc/
mkdir openvpn
cd openvpn
openvpn --genkey --secret ta.key
mkdir easy-rsa
mkdir cert</exec>
				<text>We need to copy over the reference files for easy-rsa, since OpenVPN is very picky about how it wants it's certificate authority, and other such items.</text>
				<exec>cd /usr/local/etc/openvpn/easy-rsa
cp -r /usr/local/share/doc/openvpn/easy-rsa/2.0/ .</exec>
				<text>Next up, the file vars that was moved into the directory has to be created/modified to suite your needs. You may copy the text below and paste it into a completely new file overwriting the old one</text>
				<config location="/usr/local/openvpn/easy-rsa/vars">export EASY_RSA="`pwd`"
export KEY_CONFIG="$EASY_RSA/openssl.cnf"
export KEY_DIR="/usr/local/etc/openvpn/cert"
# Issue rm -rf warning
echo NOTE: If you run ./clean-all, I will be doing a rm -rf on $KEY_DIR
export KEY_SIZE=2048
export CA_EXPIRE=3650
export KEY_EXPIRE=3650
export KEY_COUNTRY="US"
export KEY_PROVINCE="NY"
export KEY_CITY="New York"
export KEY_ORG="OrgName"
export KEY_EMAIL="email@example.net"</config>
				<text>At this point in time, if you are not using bash, you will need to switch to bash as your shell</text>
				<exec>bash</exec>
				<text>Now load the vars file you just created. It will give you a warning you may want to heed. Only do clean-all when you are certain you need it.</text>
				<exec>. ./vars</exec>
				<text>Now we can go ahead and build the required Certificate Authority and the server keys. Follow the instructions and fill in the required fields, or just hit enter if they are correct (you did set the vars file up, right?)</text>
				<exec>bash build-ca
bash build-key-server server
bash build-dh</exec>
				<text>Next up we create the beast that is the openvpn.conf file. The comments have been removed, for brevity. The OpenVPN Howto contains <link xlink:type="simple" xlink:href="http://openvpn.net/howto.html#examples" xlink:show="replace">an example config</link> file, which also explains all the options available and what they do.</text>
				<config location="/usr/local/etc/openvpn/openvpn.conf">;local a.b.c.d
port 1194
;proto tcp
proto udp
dev tun
ca cert/ca.crt
cert cert/server.crt
key cert/server.key  # This file should be kept secret
dh cert/dh2048.pem
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
;push "route 192.168.20.0 255.255.255.0"
push "redirect-gateway"
push "dhcp-option DNS 4.2.2.2"
;push "dhcp-option WINS 10.8.0.1"
keepalive 10 120

# For extra security beyond that provided
# by SSL/TLS, create an "HMAC firewall"
# to help block DoS attacks and UDP port flooding.
#
# Generate with:
#   openvpn --genkey --secret ta.key
#
# The server and each client must have
# a copy of this key.
# The second parameter should be 0
# on the server and 1 on the clients.
tls-auth ta.key 0 # This file is secret

comp-lzo
max-clients 20

user nobody
group nobody
persist-key
persist-tun
status openvpn-status.log
verb 3
mute 10</config>
				<text>Next up, we need to add it to rc.conf so that the service will be started upon boot.</text>
				<config location="/etc/rc.conf">openvpn_enable="YES"</config>
				<text>This should now allow us to start the OpenVPN service by using it's rc.d script. It won't do us much good until we generate some private/public key pairs on a client to allow them to connect. The command is included for demonstration purposes only.</text>
				<exec>/usr/local/etc/rc.d/openvpn start</exec>
				<text>For the OpenVPN client to be able to connect to the server, you need to open port 1149 protocol UDP and allow it inbound. For clients to be able to use your new OpenVPN server as their gateway (config file as created above does just that) you will need to provide some nat rules. The following included rules are for pf.</text>
				<config location="/etc/pf.conf">vpn_if="tun0"
					
nat on $ext_if from 10.8.0.0/24 to any -> ($ext_if)

pass in quick proto udp from any to port 1194 keep state label "openvpn"

# Pass stuff on the VPN interface
pass quick on $vpn_if keep state</config>
			</paragraph>
		</section>
		<section>
			<title>Client Configuration</title>
			<paragraph>
				<text>On the client we need to generate a private key, as well as a certificate signing request, or CSR. Create a new directory .openvpn to hold all the files. When OpenSSL asks you for the Organization name, you need to fill in the same value as you used to create the server key, which was also set as KEY_ORG in the vars file. When it requests a common name, use your full name, or a derivation thereof, all common names have to be unique, and if yours is not you will not be allowed to connect to the OpenVPN server.</text>
				<exec>mkdir ~/.openvpn
cd ~/.openvpn
openssl req -days 3650 -new -keyout openvpn.key -out openvpn.csr</exec>
				<text>Now you need to transfer the openvpn.csr to the server and put it in the cert directory (/usr/local/etc/openvpn/cert/), give it a meaningful name, and sign the CSR with the Certificate Authority. Use bash again. For the purposes of this guide, I have named the file example.csr</text>
				<exec>bash</exec>
				<text>And now we load vars again</text>
				<exec>cd /usr/local/etc/openvpn/easy-rsa/
. ./vars</exec>
				<text>Sign it</text>
				<exec>bash sign-req ../cert/example</exec>
				<text>After you follow the instructions, you want to grab two things from the server and transfer them back to the client. <list type="unordered">
					<item>ca.crt - Required so that your newly signed cert can be verified as being real</item>
					<item>example.crt - Was created by signing the CSR</item>
					<item>ta.key - Transfer this securely, if this falls in the wrong hands it could lead to easier breaking into encrypted streams</item>
					</list>
Rename example.crt back to openvpn.crt, so that you won't need to modify the client side config file.
				</text>
				<config location="~/.openvpn/client.conf">client
dev tun
proto udp

remote [IP address or hostname] 1194
resolv-retry infinite
nobind
persist-key
persist-tun

ca [homedir]/.openvpn/ca.crt
cert [homedir]/.openvpn/openvpn.crt
key [homedir]/.openvpn/openvpn.key

ns-cert-type server

tls-auth [homedir]/.openvpn/ta.key 1
comp-lzo
verb 3
mute 10</config>
			<text>You will need to replace [homedir] with your full path to your home directory, and change the IP address and or hostname to something that makes sense for you. If the server is publicly available over the internet and has a domain name assigned to it, you may use that instead.</text>
			<text>The client is all set to go. All you have to do now is become root (so you can dynamically allocate a tun/tap device. You can statically set a device if you want. Read the OpenVPN <link xlink:type="simple" xlink:href="http://openvpn.net/howto.html#examples" xlink:show="replace">examples</link>)</text>
			<exec>openvpn --config [homedir]/.openvpn/client.conf</exec>
			<text>If you are connected to anything like instant messaging clients, you will be disconnected as the OS starts to send packets over the new gateway.</text>
			</paragraph>
		</section>
	</body>
</guide>

=== bertjwregeer/guides/qmail.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE guide PUBLIC "-//0x58//DTD guide//EN" "http://dtd.0x58.com/guide-01.dtd">
<?xml-stylesheet href="./.guides.xsl" type="text/xsl" ?>

<guide xmlns:xlink="http://www.w3.org/1999/xlink">
	<title>qmail 1.03 with SMTP-auth</title>
	<author>
		<name>Jan-Willem Regeer</name>
		<email user="xistence" domain="x-istence.com" />
		<license url="http://creativecommons.org/licenses/by-nc-sa/2.5/" year="2005">Creative Commons Attribution-NonCommercial-ShareAlike 2.5 </license>
	</author>
	<date>2005-09-21, 20:53</date>        
	
	<body>
		<section>
			<title>General Information</title>
			<paragraph>
			<text>This guide will help you set up <link xlink:type="simple" xlink:href="http://cr.yp.to/qmail.html" xlink:show="replace">qmail 1.03</link> to recieve mail for local users, if you would like to do virtualdomains, please follow this guide, and check the links at the bottom of this guide for further material that you can use to get that up and running.</text>
			<tip>This is not the same as <link xlink:type="simple" xlink:href="http://lifewithqmail.org/" xlink:show="replace">http://lifewithqmail.org/</link>. Asking questions on the qmail mailling list about this guide, will probably get you sent to lifewithqmail. If you need help, and it is generic help, and not anything that this guide has told you to do, then don't feel bad asking them a question, all further questions about this guide should be directed towards the author.</tip>
			</paragraph>
		</section>
		<section>
			<title>Requirements</title>
			<paragraph>
				<text>You will need the following items to be able to complete this guide:
					<list type="ordered">
						<item>Root access to a FreeBSD machine</item>
						<item>FreeBSD install with <link xlink:type="simple" xlink:href="./updatingports" xlink:show="replace">ports up-to-date</link></item>
						<item><link xlink:type="simple" xlink:href="./daemontools" xlink:show="replace">Daemontools running</link></item>
					</list>
				</text>
			</paragraph>
		</section>
		<section>
			<title>Compiling</title>
			<paragraph>
				<text>This is where your up-to-date ports come in handy.</text>
				<exec>cd /usr/ports/mail/qmail
make extract patch WITH_QMAILQUEUE_PATCH=true WITH_BIG_TODO_PATCH=true WITH_OUTGOINGIP_PATCH=true WITHOUT_RCDLINK=true BATCH=yes</exec>
				<text>Now we need to get the diff file for qmail-smtpd, so that we can add in auth support</text>
				<exec>cd ./work/qmail-1.03
fetch http://0x58.com/guides/patches/qmail-smtpd-auth.patch
patch &lt; qmail-smtpd-auth.patch
cd ../..</exec>
				<text>That is it for the patching. qmail-smtpd should now be patched, and contain the necessary code for smtp-auth.</text>
				<exec>make all install</exec>
			</paragraph>
		</section>
	</body>
</guide>
